EbonAPI:RegisterSkin("VSCode", {
  parent = "AutoCallboard",

  background = 0x1F1F1F,
  accent = 0x0078D4,
  opacity = 1,
  shadow = 0.35,
  corners = 6,
  tabs = "RIGHT",

  palette = {
    bg = 0x181818,
    bgSoft = 0x313131,
    card = 0x181818,
    border = 0x2B2B2B,
    borderDim = 0x3C3C3C,
    button = 0x313131,
    buttonBorder = 0x3C3C3C,
    buttonHover = 0x0078D4,
    buttonHoverFill = 0x3C3C3C,
    buttonDisabledBorder = { 0x3C3C3C, 0.5 },
    buttonText = 0xCCCCCC,
    buttonDisabledText = { 0xCCCCCC, 0.5 },
    checkbox = 0x313131,
    checkboxBorder = 0x3C3C3C,
    checked = 0xCCCCCC,
    thumb = { 0x797979, 0.4 },
    selected = 0x04395E,
    selectedText = 0xFFFFFF,
    text = 0xCCCCCC,
    muted = 0x9D9D9D,
    title = 0xFFFFFF,
    heading = 0xE7E7E7,
    menu = 0x0078D4,
    focus = 0x0078D4,
    rowHover = 0x2A2D2E,
    headerBg = { 0x181818, 0 },
    navBg = 0x1F1F1F,
    pageBg = 0x1F1F1F,
    footerBg = { 0x181818, 0 },
  },

  fonts = {
    small = { file = "Fonts\\ARIALN.TTF", size = 11 },
    normal = { file = "Fonts\\ARIALN.TTF" },
    large = { file = "Fonts\\ARIALN.TTF", size = 18 },
    button = { file = "Fonts\\ARIALN.TTF", size = 12, outline = "NONE" },
    shadow = { alpha = 0 },
  },

  border = {
    round = { small = 6 },
  },

  window = {
    padding = 5,
    spacing = 5,
    shadow = { base = 6, spread = 16, alphaBase = 0.2, alphaSpread = 0.4, y = -2 },
  },

  header = {
    height = 30,
    inset = -5,
    spacing = 0,
    title = { x = 8, y = 9, font = "normal", color = "text" },
    version = { gap = 6, y = 0 },
    search = { position = "CENTER", width = 300, height = 20, insetY = 1 },
    close = { brick = "flat", size = 30, width = 40, y = 0, glyph = "×" },
    minimize = { show = true, width = 40, glyph = "—" },
    sidebar = { show = true, size = 14, width = 24 },
    history = { show = true, back = "←", forward = "→", width = 24 },
    rule = { show = false },
  },

  footer = {
    show = true,
    rule = false,
    badge = { show = true },
    items = true,
    gap = 12,
  },

  nav = {
    width = 220,
    inset = 0,
    padding = 6,
    frame = "LARGE",
    rail = { show = true, gap = 5, spacing = 6, dim = 0.55 },
    tree = { collapsible = true, guides = true },
    section = { x = 8, height = 26, color = "text", font = "normal" },
    tab = { brick = "list", height = 22, gap = 0, align = "LEFT", font = "normal", padding = 20 },
  },

  page = {
    width = 640,
    height = 540,
    gutter = 12,
    top = 40,
    frame = "LARGE",
    close = { size = 30, width = 40, glyph = "×" },
    inset = { x = 22, y = 10 },
    title = { y = 0, color = "title" },
    description = { gap = 4, below = 2 },
    unit = 240,
    gap = { x = 12, y = 16 },
    layout = "LIST",
    descriptions = "INLINE",
    strip = { show = true, height = 30, tabs = 6, color = "card", idle = "card", separator = "border" },
    crumbs = { show = true, height = 22, separator = "›" },
  },

  widgets = {
    button = { padding = 10 },
    toggle = {
      height = 20, size = 14, gap = 8, mark = -3,
      markTexture = "Interface\\Buttons\\UI-CheckBox-Check",
    },
    range = {
      height = 46, top = 16, bar = 12, track = 2, fill = true, fillColor = "focus",
      thumb = { width = 6, height = 12 },
      edit = { width = 50, height = 18 },
    },
    select = { height = 40 },
    menu = { brick = "list", gap = 0, padding = 2, inset = 10, title = { align = "LEFT" } },
    heading = { lines = "NONE", color = "title", height = 26 },
    group = { brick = "plain", padding = 0, title = 22, titleX = 0, color = "title", frame = "FLAT" },
    scroll = { width = 8, thumb = 30, trackAlpha = 0 },
  },

  chat = {
    prefix = 0x0078D4,
    text = 0xCCCCCC,
    muted = 0x9D9D9D,
  },
})
